//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZKWeb.Toolkits.ProjectCreator.Cmd.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZKWeb.Toolkits.ProjectCreator.Cmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AspNet, AspNetCore or Owin 的本地化字符串。
        /// </summary>
        internal static string AspNetAspNetCoreOrOwin {
            get {
                return ResourceManager.GetString("AspNetAspNetCoreOrOwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dapper, EFCore, MongoDB or NHibernate 的本地化字符串。
        /// </summary>
        internal static string DapperEFCoreMongoDBOrNHibernate {
            get {
                return ResourceManager.GetString("DapperEFCoreMongoDBOrNHibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSSQL, MySQL, SQLite, MongoDB or PostgreSQL 的本地化字符串。
        /// </summary>
        internal static string MSSQLMySQLSQLiteMongoDBOrPostgreSQL {
            get {
                return ResourceManager.GetString("MSSQLMySQLSQLiteMongoDBOrPostgreSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output directory 的本地化字符串。
        /// </summary>
        internal static string OutputDirectory {
            get {
                return ResourceManager.GetString("OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project description 的本地化字符串。
        /// </summary>
        internal static string ProjectDescription {
            get {
                return ResourceManager.GetString("ProjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project name 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show this message and exit 的本地化字符串。
        /// </summary>
        internal static string ShowThisMessageAndExit {
            get {
                return ResourceManager.GetString("ShowThisMessageAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The connection string 的本地化字符串。
        /// </summary>
        internal static string TheConnectionString {
            get {
                return ResourceManager.GetString("TheConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The location of plugin.collection.json, if you want to use default plugins 的本地化字符串。
        /// </summary>
        internal static string TheLocationOfPluginCollectionJson {
            get {
                return ResourceManager.GetString("TheLocationOfPluginCollectionJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try `ProjectCreator --help` for more information 的本地化字符串。
        /// </summary>
        internal static string TryProjectCreatorHelpForMoreInformation {
            get {
                return ResourceManager.GetString("TryProjectCreatorHelpForMoreInformation", resourceCulture);
            }
        }
    }
}
