//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZKWeb.Toolkits.WebsitePublisher.Cmd.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZKWeb.Toolkits.WebsitePublisher.Cmd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore pattern in regex 的本地化字符串。
        /// </summary>
        internal static string IgnorePatternInRegex {
            get {
                return ResourceManager.GetString("IgnorePatternInRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show this message and exit 的本地化字符串。
        /// </summary>
        internal static string ShowThisMessageAndExit {
            get {
                return ResourceManager.GetString("ShowThisMessageAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output directory 的本地化字符串。
        /// </summary>
        internal static string TheOutputDirectory {
            get {
                return ResourceManager.GetString("TheOutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The output name 的本地化字符串。
        /// </summary>
        internal static string TheOutputName {
            get {
                return ResourceManager.GetString("TheOutputName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The source website root directory 的本地化字符串。
        /// </summary>
        internal static string TheSourceWebsiteRootDirectory {
            get {
                return ResourceManager.GetString("TheSourceWebsiteRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try `WebsitePublisher --help` for more information 的本地化字符串。
        /// </summary>
        internal static string TryWebsitePublisherHelpForMoreInformation {
            get {
                return ResourceManager.GetString("TryWebsitePublisherHelpForMoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Which configuration to publish 的本地化字符串。
        /// </summary>
        internal static string WhichConfigurationToPublish {
            get {
                return ResourceManager.GetString("WhichConfigurationToPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Which framework to publish 的本地化字符串。
        /// </summary>
        internal static string WhichFrameworkToPublish {
            get {
                return ResourceManager.GetString("WhichFrameworkToPublish", resourceCulture);
            }
        }
    }
}
