//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZKWeb.Toolkits.ProjectCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZKWeb.Toolkits.ProjectCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Connection string can&apos;t be empty 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringCantBeEmpty {
            get {
                return ResourceManager.GetString("ConnectionStringCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Database must be one of  的本地化字符串。
        /// </summary>
        internal static string DatabaseMustBeOneOf {
            get {
                return ResourceManager.GetString("DatabaseMustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detect templates directory failed 的本地化字符串。
        /// </summary>
        internal static string DetectTemplatesDirectoryFailed {
            get {
                return ResourceManager.GetString("DetectTemplatesDirectoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ORM must be one of  的本地化字符串。
        /// </summary>
        internal static string ORMMustBeOneOf {
            get {
                return ResourceManager.GetString("ORMMustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output directory can&apos;t be empty 的本地化字符串。
        /// </summary>
        internal static string OutputDirectoryCantBeEmpty {
            get {
                return ResourceManager.GetString("OutputDirectoryCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project name can&apos;t be empty 的本地化字符串。
        /// </summary>
        internal static string ProjectNameCantBeEmpty {
            get {
                return ResourceManager.GetString("ProjectNameCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project type must be one of  的本地化字符串。
        /// </summary>
        internal static string ProjectTypeMustBeOneOf {
            get {
                return ResourceManager.GetString("ProjectTypeMustBeOneOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This plugin collection only support these ORM:  的本地化字符串。
        /// </summary>
        internal static string ThisPluginCollectionOnlySupportTheseORM {
            get {
                return ResourceManager.GetString("ThisPluginCollectionOnlySupportTheseORM", resourceCulture);
            }
        }
    }
}
